# permissions for end users to view prephemeralenvcontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prephemeralenvcontroller-viewer-role
rules:
- apiGroups:
  - prcontroller.ephemeralenv.io.prcontroller.ephemeralenv.io
  resources:
  - prephemeralenvcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - prcontroller.ephemeralenv.io.prcontroller.ephemeralenv.io
  resources:
  - prephemeralenvcontrollers/status
  verbs:
  - get
